AdvancedOptions: false
RuntimeType: Container
DockerFilePath: Dockerfile
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: cn-hangzhou
RepoName: newmarouane/FlareSolverr
RegionId: ap-southeast-1
CustomParameters: ''
Owner: newmarouane
Branch: master
Platform: github
