Service:
  RegionId: ap-southeast-1
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
    - TemplateName: ECS单机版
      SupportOperations:
      - Start
      - Stop
      - Restart
    SupportBackup: true
    ModifyParametersConfig:
    - TemplateName: ECS单机版
      Operation:
      - Name: 变更ECS实例规格
        Description: 变更ECS实例规格
        Type: Custom
        Parameters:
        - EcsInstanceType
      - Name: 变更ECS实例密码
        Description: 变更ECS实例密码
        Type: Custom
        Parameters:
        - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
        - cn-hangzhou
      ArtifactRelation:
        ecs_image_FlareSolverr:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
    - Name: ECS单机版
      Url: 'ros_templates/template.yaml'
      ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
      AllowedRegions:
      - cn-hangzhou
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
  - Locale: zh-CN
    Name: newmarouane/FlareSolverr-d4qe
    ShortDescription: Service description
    Image: 
      https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1853370294850618/service-image/bfd30cc4-e959-4093-b5cb-77a05058b911.png
    Softwares: []
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_FlareSolverr
    Description: FlareSolverr EcsImage
    SupportRegionIds:
    - cn-hangzhou
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: newmarouane
        RepoName: newmarouane/FlareSolverr
        Branch: master
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      CommandContent: |-
        docker build  -f Dockerfile -t newmarouane/flaresolverr .  2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded';
